"use client";
import {FormEvent,useEffect,useState} from "react";
import {api} from "@/lib/api"; import {Heading,Empty} from "@/components/PageParts";
type Vehicle={id:number;customer_id:number;vehicle_code:string;registration_number:string;make:string;model:string;manufactured_year:number;colour:string;status:string};
type Customer={id:number;full_name:string;customer_code:string};
export default function Vehicles(){const[rows,setRows]=useState<Vehicle[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[msg,setMsg]=useState("");
 const load=()=>api<Vehicle[]>("/api/vehicles").then(setRows).catch(e=>setMsg(e.message)); useEffect(()=>{load();api<Customer[]>("/api/customers").then(setCustomers).catch(()=>null)},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));try{await api("/api/vehicles",{method:"POST",body:JSON.stringify({...o,customer_id:Number(o.customer_id),manufactured_year:o.manufactured_year?Number(o.manufactured_year):null})});setMsg("Vehicle registered.");e.currentTarget.reset();load()}catch(err){setMsg(err instanceof Error?err.message:"Unable to register vehicle.")}}
 return <><Heading eyebrow="VEHICLES" title="Insured vehicles" description="Register vehicles and link them to their policyholder."/>
 {customers.length>0&&<section className="panel"><h2>Register vehicle</h2><form className="formGrid" onSubmit={submit}><label>Customer<select name="customer_id" required>{customers.map(c=><option value={c.id} key={c.id}>{c.full_name} · {c.customer_code}</option>)}</select></label><label>Registration number<input name="registration_number" required/></label><label>Make<input name="make" required/></label><label>Model<input name="model" required/></label><label>Colour<input name="colour" required/></label><label>Year<input name="manufactured_year" type="number"/></label><button className="primary">Register vehicle</button></form>{msg&&<div className="alert">{msg}</div>}</section>}
 <section className="cardGrid">{rows.map(v=><article className="vehicleCard" key={v.id}><div className="plate">{v.registration_number}</div><h3>{v.make} {v.model}</h3><p>{v.colour}{v.manufactured_year?` · ${v.manufactured_year}`:""}</p><span className="status ok">{v.status}</span></article>)}</section>{!rows.length&&<Empty title="No vehicles found" text="Registered vehicles will appear here."/>}</>}
